---
- name: configure router interfaces and routes
  hosts: cisco-csr
  connection: network_cli
  gather_facts: no
  become: yes
  tasks:
  - name: Configure Interface
    ios_l3_interface:
      name: "{{ item.name }}"
      ipv4: "{{ item.ipv4_addr }}"
    with_items: "{{ interfaces | default([]) }}"
    notify: "save ios"

  - name: Enable Interface
    ios_interface:
      name: "{{ item.name }}"
      enabled: "{{ item.enabled }}"
      state: "{{ item.state }}"
    with_items: "{{ interfaces | default([]) }}"
    notify: "save ios"

  - name: Remove Static Route
    ios_static_route:
      prefix: "{{ item.prefix }}"
      mask: "{{ item.mask }}"
      next_hop: "{{ item.next_hop }}"
      state: absent
    with_items: "{{ static_routes | default([]) }}"
    notify: "save ios"

  - name: Enable OSPF
    ios_config:
      lines: "{{ ospf_networks.parent }}"
      timeout: 60
    notify: "save ios"

  - name: Configure OSPF
    ios_config:
      lines: "{{ ospf_networks.commands }}"
      parents: "{{ ospf_networks.parent }}"
      timeout: 60
    notify: "save ios"

  handlers:
  - name: save ios
    ios_command:
      commands: "write mem"
      timeout: 60
    when: not ansible_check_mode

- name: Run Test Cases
  hosts: "cisco-csr"
  connection: network_cli
  gather_facts: no
  become: yes
  tasks:
  - name: Wait 30 seconds
    pause:
      seconds: 30

  - name: Verify OSPF neighbors
    ios_command:
      commands:
        - "show ip ospf neighbor"
    register: ospf_results

  - name: Test reachability
    ios_command:
      commands:
        - "ping 192.168.3.2"
        - "ping 192.168.3.3"
        - "ping 192.168.4.2"
        - "ping 192.168.4.3"
    register: ping_result

  - name: Evaluate test results
    assert:
      that:
        - "ping_result.stdout[0] != ''"
        - "'192.168.3.2' in ping_result.stdout[0]"
        - "'Success rate is 100 percent' in ping_result.stdout[0]"
        - "'192.168.3.3' in ping_result.stdout[1]"
        - "'Success rate is 100 percent' in ping_result.stdout[1]"
        - "'192.168.4.2' in ping_result.stdout[2]"
        - "'Success rate is 100 percent' in ping_result.stdout[2]"
        - "'192.168.4.3' in ping_result.stdout[3]"
        - "'Success rate is 100 percent' in ping_result.stdout[3]"
