---
- name: Configure Device Base Configurations
  hosts: cisco-csr
  connection: network_cli
  gather_facts: no
  become: yes
  tasks:
  - name: Configure Hostname and DNS
    ios_system:
      hostname: "{{ inventory_hostname_short }}"
      name_servers: "{{ dns_servers }}"
      timeout: 60
    notify: "save ios"

  - name: Set Login Banner
    ios_banner:
      banner: login
      text: "{{ login_banner }}"
      timeout: 60
    notify: "save ios"

  - name: Configure NTP
    ios_config:
      lines: "{{ ntp.commands }}"
      timeout: 60
    notify: "save ios"

  - name: Configure SNMP
    ios_config:
      lines: "{{ snmp.commands }}"
      timeout: 60
    notify: "save ios"

  handlers:
  - name: save ios
    ios_command:
      commands: "write mem"
      timeout: 60
    when: not ansible_check_mode
