---
- name: Generate interface report
  hosts: cisco-csr
  gather_facts: no
  connection: network_cli

  roles:
    - ansible-network.network-engine

  tasks:
    - name: Capture show ip interface brief
      ios_command:
        commands:
          - show ip interface brief
      register: output

    - name: Parse command output
      command_parser:
        file: "parsers/show_ip_interface_brief.yaml"
        content: "{{ output.stdout[0] }}"

    - name: Create reports directory
      file:
        path: reports
        state: directory
        mode: 0755
      run_once: True

    - name: Convert parse data to YAML
      template:
        src: templates/show_ip_interface_brief.j2
        dest: "reports/{{ inventory_hostname }}"
